### ISSUE TITLE
Cleanups added with addCleanup incorrectly called on subsequent runs when using `trial -u`

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10262] opened 2021-10-04 08:28 UTC
|[<img alt="cjw296's avatar" src="https://avatars.githubusercontent.com/u/632049?s=50" width="50" height="50">](https://github.com/cjw296)| @cjw296 reported|
|-|-|
|Trac ID|trac#10262|
|Type|defect|
|Created|2021-10-04 08:28:01Z|

Reproducer:

```
from twisted.trial.unittest import TestCase


class StatefulCleanup:

    called = False

    def __call__(self):
        if self.called:
            raise AssertionError('Called more than once')
        self.called = True


class TestAddCleanup(TestCase):

    def setUp(self):
        self.addCleanup(StatefulCleanup())

    def testIt(self):
        pass
```

If run with trial -u, the AssertionError will be issued.

<details><summary>Searchable metadata</summary>

```
trac-id__10262 10262
type__defect defect
reporter__cjw296 cjw296
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1633336081438120 1633336081438120
changetime__1633366700335758 1633366700335758
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment] 2021-10-04 16:58
|[<img alt="cjw296's avatar" src="https://avatars.githubusercontent.com/u/632049?s=50" width="50" height="50">](https://github.com/cjw296)<a name="note_1"></a>|@cjw296 commented|
|-|-|

Workaround:


```
from twisted.trial.unittest import TestCase as TwistedTestCase


class TestCase(TwistedTestCase):

    def run(self, result):
        # https://twistedmatrix.com/trac/ticket/10262
        self._cleanups[:] = []
        super().run(result)
```

**Comment by exarkun** [comment] 2022-09-07 01:16
https://github.com/twisted/twisted/issues/10320 was a duplicate of this.

**Closed as completed by exarkun** 2022-09-07 01:16 UTC
Labels: bug, priority-normal, new, trial
