### ISSUE TITLE
twisted.protocols.amp.TooLong

### ISSUE THREAD

**Issue by vforvilela** [twisted/twisted#12342] opened 2024-10-19 16:32 UTC
**Describe the incorrect behavior you saw**
`twisted.protocols.amp.TooLong`

**Describe how to cause this behavior**
Sending a message larger than 2 ** 16 chars

**What did you do to get it to happen?**
Happens everytime I call `AMP.callRemote()` with a larger than 2 ** 16 chars message.

```
  ...
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 951, in callRemote
    return co._doCommand(self)
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 1973, in _doCommand
    d = proto._sendBoxCommand(
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 884, in _sendBoxCommand
    box._sendTo(self.boxSender)
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 713, in _sendTo
    proto.sendBox(self)
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 2358, in sendBox
    self.transport.write(box.serialize())
  File "/venv/lib/python3.10/site-packages/twisted/protocols/amp.py", line 692, in serialize
    raise TooLong(False, True, v, k)
twisted.protocols.amp.TooLong:
```

**Additional context**
```
$ pip show Twisted
Name: Twisted
Version: 24.7.0
...
```

**Comment by adiroiban** [comment] 2024-10-19 23:01
Thanks for the report.

My understanding is that this "works as designed" and this is not a bug.

That is, the AMP protocol has no support for sending large messages.

See the documentation at https://docs.twisted.org/en/latest/api/twisted.protocols.amp.html

> Values are limited to the maximum encodable size in a 16-bit length, 65535 bytes.


--------

Is there any place in the documentation where you found that large messages are supported ?


I am closing this for now.

Feel free to add more feedback.

Please also check https://github.com/twisted/twisted/issues/9488 which is targeted at adding support for larger messages.

There are talks about creating AMP v2

**Closed as not planned by adiroiban** 2024-10-19 23:01 UTC
Labels: bug

**Comment by glyph** [comment] 2024-10-20 19:08
We could potentially re-open this by fixing the parameter type to have a configurable length maximum rather than an arbitrary length maximum. But allowing parameters to be unlimited size by default is definitely not a good plan.
