### ISSUE TITLE
[IMPORTANT] reactor multi-thread-bug-like issue

### ISSUE THREAD

**Issue by Pborz** [twisted/twisted#11881] opened 2023-06-18 06:52 UTC
code structure:
a ws based thread
```
class WsConnectManager(threading.Thread):

    def __init__(self, url, isPrivate):
        threading.Thread.__init__(self)
```
its run() method let the reactor run:
```
    def run(self):
        reactor.run(installSignalHandlers=False)
```

in the sub class of the wsconnect,all a b c are individual new object of the class, there is a run_ to let them several thread run:
```
    def _run_exchange_connection(self):
        self.a.start()
        self.b.start()
        self.c.start()
```

**BUG START HERE BELOW** 

when `_run_exchange_connection`, a started, but b and c turned out to be:

```
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/twisted/internet/base.py", line 841, in startRunning
    raise error.ReactorAlreadyRunning()
twisted.internet.error.ReactorAlreadyRunning
    raise error.ReactorAlreadyRunning()
```

actually a b c all are individual reactor of thread, but raised these alreadrunning error? IT IS AN HUGE FATAL BUG

**Comment by adiroiban** [comment] 2023-06-18 10:47
Hi. Thanks for the report.

Can you  please provide a full example that we can use to reproduce this error.

I assume you are very familiar with all the information from this page https://docs.twisted.org/en/stable/core/howto/threading.html

What is `wsconnect` ?

Is your WsConnectManager the main thread (`.setDaemon(True)`) ?

From the current information I don't know how to reproduce this error.

Regards

**Comment by Pborz** [comment] 2023-06-18 11:08
first, I can provide a full example that we can use to reproduce this error. but since that I consider this is somehow a basic concept-like error so I decided to just lightly describe above in a simplified way. if not enough like now, I would easily explain further but
second, I still prefer to discuss it in words: if there is a class based on Thread, and its run() could contain single line just reactor.run() right? 
third, now we could let this object of thread called ‘a’ “.start”. but when we new an object called ‘b’, it just individual right? then when b.start(), error occurs. WHY? different thread different reactor.

because not simplifying the structure, we may spend lines in describing the code structure. but if the problem is so simple, I think we could just discuss with simplified way. 

if you team still not prefer to reproduce this simple thread issue, then I shall just do the details later.  THX

**Comment by exarkun** [comment] 2023-06-19 01:05
Only a single reactor per process is supported.  The pattern you describe, where a process has multiple threads and each thread has its own reactor, is not supported.

If someone were to implement support for this and contribute to to Twisted, it is likely that this could be accepted.  For now, I'm closing this issue because I think the report is about a misunderstanding of what is supported in Twisted - not an offer to implement the feature.

**Closed as completed by exarkun** 2023-06-19 01:05 UTC
Labels: bug
