### ISSUE TITLE
Incompatibility with attrs < 21.3.0

### ISSUE THREAD

**Issue by carlwgeorge** [twisted/twisted#11839] opened 2023-04-04 02:48 UTC
**Describe the incorrect behavior you saw**
Twisted imports `from attrs` in several locations.  The `attrs` namespace wasn't added to the attrs module until [version 21.3.0](https://www.attrs.org/en/21.3.0/changelog.html).  Twisted claims to be compatible with [`attrs >= 19.20`](https://github.com/twisted/twisted/blob/twisted-22.10.0/setup.cfg#L35).

**Describe how to cause this behavior**
I was working on [packaging crochet in EPEL 9](https://bugzilla.redhat.com/show_bug.cgi?id=2179155) (for use on RHEL 9), when I realized that the packaged version of twisted (22.10.0) wasn't compatible with the packaged version of attrs (20.3.0).  A small reproducer is to install those versions of twisted and attrs, then try to import something from twisted that uses `from attrs`.

```
python3 -m venv .env
. .env/bin/activate
pip install twisted==22.10.0 attrs==20.3.0
python -c 'import twisted.python.systemd'
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/carl/repro/.env/lib64/python3.9/site-packages/twisted/python/systemd.py", line 18, in <module>
    from attrs import Factory, define
ModuleNotFoundError: No module named 'attrs'
```

**Describe the correct behavior you'd like to see**
I think that twisted should either set the minimum version of attrs to 21.3.0 (the version that introduced the `attrs` namespace), or adjust the imports to `from attr` to use the old import path.  I'm happy to send a PR to implement either of these depending on which approach the project would prefer.

**Testing environment**
 - Operating System and Version; paste the output of these commands:
```
[carl@yellow:~]$ uname -a
Linux yellow 5.14.0-289.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Mar 19 07:28:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[carl@yellow:~]$ cat /etc/os-release 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
 - Twisted version [e.g. 22.2.0]
```
attrs==20.3.0
Automat==22.10.0
constantly==15.1.0
hyperlink==21.0.0
idna==2.10
incremental==21.3.0
six==1.15.0
Twisted==22.10.0
typing_extensions==4.4.0
zope.interface==5.4.0
```

**Comment by adiroiban** [comment] 2023-04-04 03:31
Hi.

Thanks for the report.

This looks like a duplicate of #11737

Which was already fixed in #11741

but not released
 
https://github.com/twisted/twisted/blob/525da4a0becad1e814c74f12c365f15fe9cd10de/pyproject.toml#L37-L39

I guess we are close to 6 months since the last release, so we might make a new release.

I am closing this.
Please reopen if you think I am wrong and this is not yet fixed.

**Comment by carlwgeorge** [comment] 2023-04-04 03:48
Ah, I missed that in trunk, thanks for pointing it out.  I can carry a downstream patch in EPEL9 to switch to the old import path, as it's unlikely that RHEL9 will update attrs to a newer version.

**Comment by twm** [comment] 2023-04-18 04:48
Closing this as it looks like Adi forgot to hit the button. :) Thanks!

**Closed as completed by twm** 2023-04-18 04:48 UTC
Labels: bug
