### ISSUE TITLE
require `setuptools>=62` to avoid `pkg_resources.DistributionNotFound: The 'zope-interface>=5' distribution was not found and is required by Twisted` on old Python installs

### ISSUE THREAD

**Issue by MatthijsBurgh** [twisted/twisted#11935] opened 2023-08-30 07:46 UTC
**Describe the incorrect behavior you saw**
When loading an entry_point, which depends on Twisted, I get an `pkg_resources.DistributionNotFound` error. This bug was introduced since the release 23.8.0

**Describe how to cause this behavior**
It bug is consistent. My CI, https://github.com/tue-robotics/tue-robotics.github.io,  is failing every time.

The installed pip packages:
```bash
Successfully installed
CacheControl-0.13.1
Jinja2-3.1.2
MarkupSafe-2.1.3
Pygments-2.16.1
Twisted-23.8.0
anyascii-0.3.2
appdirs-1.4.4
astor-0.8.1
astroid-2.15.6
attrs-23.1.0
automat-22.10.0
babel-2.12.1
catkin-sphinx-0.3.2
catkin-tools-document-0.5.2
charset-normalizer-3.2.0
configargparse-1.7
constantly-15.1.0
docutils-0.18.1
epydoc-3.0.1
filelock-3.12.3
hyperlink-21.0.0
imagesize-1.4.1
importlib-metadata-6.8.0
importlib-resources-6.0.1
incremental-22.10.0
lazy-object-proxy-1.9.0
lunr-0.6.2
msgpack-1.0.5
packaging-23.1
pydoctor-23.4.1
requests-2.31.0
snowballstemmer-2.2.0
sphinx-7.1.2
sphinx-autoapi-2.1.1
sphinx-rtd-theme-1.3.0
sphinxcontrib-applehelp-1.0.4
sphinxcontrib-devhelp-1.0.2
sphinxcontrib-htmlhelp-2.0.1
sphinxcontrib-jquery-4.1
sphinxcontrib-jsmath-1.0.1
sphinxcontrib-qthelp-1.0.3
sphinxcontrib-serializinghtml-1.1.5
toml-0.10.2
typing-extensions-4.7.1
wrapt-1.15.0
zipp-3.16.2
zope-interface-6.0
```

```py
Traceback (most recent call last):
  File "/usr/bin/catkin", line 33, in <module>
    sys.exit(load_entry_point('catkin-tools==0.9.2', 'console_scripts', 'catkin')())
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 164, in catkin_main
    argument_preprocessors = create_subparsers(parser, verbs)
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 56, in create_subparsers
    desc = load_verb_description(verb)
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 43, in load_verb_description
    return entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zope-interface>=5' distribution was not found and is required by Twisted
```
Sorry, I am not able to generate a simple test example for now.

**Describe the correct behavior you'd like to see**
Correct detection of the dependencies.

**Testing environment**
 - Operating System and Version: `Ubuntu 20.04 Docker, host Ubuntu 22.04, kernel 5.15.0-1041-azure`
 - Twisted version: `23.8.0`

**Additional context**
Could the issue be in `zope-interface` vs. `zope.interface`?

**Comment by adiroiban** [comment] 2023-08-30 09:09
Thanks for the report.
Not sure what is going on there


Our automated tests are executed  on Ubuntu 20.04 VMs.

Can you try to reproduce this outside of your deployment pipeline?
Maybe there is some caching....or you need to update pip.

I did a quick test on my Ubuntu 22.04 with python 3.10 and it works.

```
$ cd /home/adi/tmp/
$ virtualenv test
created virtual environment CPython3.10.12.final.0-64 in 192ms
  creator CPython3Posix(dest=/home/adi/tmp/test, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/adi/Dropbox/.local/share/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.0.0, wheel==0.41.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ . test/bin/activate
$ pip install twisted

Collecting twisted
  Obtaining dependency information for twisted from https://files.pythonhosted.org/packages/2a/e3/9fe9cf016d32d050a2eec518c2f5156f7623b42e1ef3f2fa3e80c0ef654c/twisted-23.8.0-py3-none-any.whl.metadata
  Downloading twisted-23.8.0-py3-none-any.whl.metadata (10.0 kB)
Collecting attrs>=21.3.0 (from twisted)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting automat>=0.8.0 (from twisted)
  Using cached Automat-22.10.0-py2.py3-none-any.whl (26 kB)
Collecting constantly>=15.1 (from twisted)
  Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting hyperlink>=17.1.1 (from twisted)
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting incremental>=22.10.0 (from twisted)
  Using cached incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Collecting typing-extensions>=3.10.0 (from twisted)
  Obtaining dependency information for typing-extensions>=3.10.0 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting zope-interface>=5 (from twisted)
  Using cached zope.interface-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
Collecting six (from automat>=0.8.0->twisted)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna>=2.5 (from hyperlink>=17.1.1->twisted)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools in ./test/lib/python3.10/site-packages (from zope-interface>=5->twisted) (68.0.0)
Downloading twisted-23.8.0-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 9.9 MB/s eta 0:00:00
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: incremental, constantly, zope-interface, typing-extensions, six, idna, attrs, hyperlink, automat, twisted
Successfully installed attrs-23.1.0 automat-22.10.0 constantly-15.1.0 hyperlink-21.0.0 idna-3.4 incremental-22.10.0 six-1.16.0 twisted-23.8.0 typing-extensions-4.7.1 zope-interface-6.0

```

**Comment by MatthijsBurgh** [comment] 2023-08-30 09:26
The problem is also not that zope-interface-6.0 is not installed correctly. But when loading the entry_point, something is going wrong.

I hope I will find some time later this week to test it on my Ubuntu 20.04 machine.

**Comment by adiroiban** [comment] 2023-08-30 14:43
ok... so the issue might be with twisted and [catkin_tools](https://github.com/catkin/catkin_tools)

I know that recently there was work to remove the  usage of `pkg_resources` which is expected to be depreated.

but I think that is important to have  twisted work with any other standard packaging tool

If you can generate a short example to reproduce this, that would help a lot.

thanks

**Comment by glyph** [comment] 2023-08-30 18:46
@MatthijsBurgh can you minimize this example into a series of commands? I don't think we can debug your CI for you, but if you a small script to load the entrypoint in question, and it reproduces after simply `pip install`ing the list of requirements, I think we could investigate

**Comment by MatthijsBurgh** [comment] 2023-08-31 06:48
@glyph Hopefully this enough for you to debug it. I never wanted you to debug my CI. It is way too custom.

I have a small set of commands to do, start with an ubuntu:20.04 docker image:
```bash
apt-get update
apt-get install python3-pip
pip install catkin-tools-document
catkin --help
```
The pip install resulted in these packages:
```
alabaster==0.7.13
appdirs==1.4.4
astor==0.8.1
attrs==23.1.0
Automat==22.10.0
Babel==2.12.1
cachecontrol==0.13.1
catkin-pkg==0.5.2
catkin-sphinx==0.3.2
catkin-tools==0.9.4
catkin-tools-document==0.5.2
certifi==2023.7.22
charset-normalizer==3.2.0
ConfigArgParse==1.7
constantly==15.1.0
docutils==0.20.1
filelock==3.12.3
hyperlink==21.0.0
idna==3.4
imagesize==1.4.1
importlib-metadata==6.8.0
importlib-resources==6.0.1
incremental==22.10.0
Jinja2==3.1.2
lunr==0.6.2
MarkupSafe==2.1.3
msgpack==1.0.5
osrf-pycommon==2.0.2
packaging==23.1
pydoctor==23.4.1
Pygments==2.16.1
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
snowballstemmer==2.2.0
sphinx==7.1.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
toml==0.10.2
twisted==23.8.0
typing-extensions==4.7.1
urllib3==1.26.16
zipp==3.16.2
zope.interface==6.0
```
I produced the same error.
```py
catkin --help    
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 164, in catkin_main
    argument_preprocessors = create_subparsers(parser, verbs)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 56, in create_subparsers
    desc = load_verb_description(verb)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 43, in load_verb_description
    return entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zope-interface>=5' distribution was not found and is required by Twisted
```

When forcing an older version of twisted, `pip install 'twisted<23'`, `catkin --help` doesn't result in an error. While stil having `zope.interface==6.0`.

**Comment by bj00rn** [comment] 2023-08-31 07:17
Maybe unrelated.. pipdeptree is complaining about unresolved dependency zope-interface since yesterday.

### Twisted 23.8.0 (pipdeptree fails)

```shell
$ uname -a
Darwin xxx.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.36/RELEASE_X86_64 x86_64
```

```
$ python --version
Python 3.9.16
```

```
$ pip --version
pip 23.2.1 from /Users/xxx/.pyenv/versions/3.9.16/envs/xxx/lib/python3.9/site-packages/pip (python 3.9)
```

```
$ pipdeptree --version
2.2.0
```

```
$ pip install -r requirements.txt
[....]
Successfully installed Django-3.2.19 PyJWT-2.8.0 PyYAML-6.0.1 adal-1.2.7 aioredis-1.3.1 anyio-3.7.1 appnope-0.1.3 asgiref-3.7.2 astroid-2.13.5 asttokens-2.2.1 async-timeout-4.0.3 attrs-23.1.0 autobahn-23.6.2 automat-22.10.0 backcall-0.2.0 beautifulsoup4-4.12.2 black-22.3.0 certifi-2023.7.22 cffi-1.15.1 cfgv-3.4.0 channels-3.0.4 channels-redis-3.4.0 charset-normalizer-3.2.0 click-8.1.7 colorclass-2.2.2 constantly-15.1.0 cryptography-41.0.3 daphne-3.0.2 decorator-5.1.1 defusedxml-0.7.1 dill-0.3.7 distlib-0.3.7 django-activity-stream-1.4.0 django-anymail-8.6 django-common-helpers-0.9.1 django-cors-headers-3.7.0 django-cron-0.5.1 django-defender-0.9.1 django-eml-email-backend-0.1 django-guardian-2.4.0 django-log-request-id-2.0.0 django-otp-1.1.3 django-redis-sessions-0.6.2 django-render-block-0.9.2 django-softdelete-0.9.2 django-templated-email-2.3.0 django-templated-mail-1.1.1 djangorestframework-3.12.4 djangorestframework-simplejwt-5.0.0 djoser-2.2.0 docopt-0.6.2 dparse-0.6.3 draftjs_exporter-5.0.0 drf-nested-routers-0.93.4 ecdsa-0.18.0 et-xmlfile-1.1.0 exceptiongroup-1.1.3 executing-1.2.0 filelock-3.12.3 flake8-3.9.2 gunicorn-20.1.0 h11-0.14.0 hiredis-2.2.3 html2text-2020.1.16 html5lib-1.1 httptools-0.6.0 hyperlink-21.0.0 identify-2.5.27 idna-3.4 incremental-22.10.0 ipython-8.10.0 isort-5.9.2 jedi-0.19.0 jsonschema-4.5.0 lazy-object-proxy-1.9.0 matplotlib-inline-0.1.6 mccabe-0.6.1 msgpack-1.0.5 mypy-extensions-1.0.0 nodeenv-1.8.0 oauthlib-3.2.2 openpyxl-3.0.10 packaging-23.1 parso-0.8.3 pathspec-0.11.2 pexpect-4.8.0 pickleshare-0.7.5 pip-upgrader-1.4.15 pipdeptree-2.2.0 platformdirs-3.10.0 pre-commit-2.13.0 prompt-toolkit-3.0.39 psycopg2-2.9.3 ptyprocess-0.7.0 pure-eval-0.2.2 pyPEG2-2.15.2 pyasn1-0.5.0 pyasn1-modules-0.3.0 pycodestyle-2.7.0 pycparser-2.21 pydantic-1.9.1 pyflakes-2.3.1 pygments-2.16.1 pylint-2.15.3 pylint-django-2.5.3 pylint-plugin-utils-0.7 pyopenssl-23.2.0 pyrsistent-0.19.3 python-dateutil-2.8.2 python-dotenv-1.0.0 python-jose-3.3.0 python-json-logger-2.0.2 python3-openid-3.2.0 pytz-2021.3 redis-4.5.5 requests-2.31.0 requests-oauthlib-1.3.1 rsa-4.9 safety-1.10.3 service-identity-23.1.0 six-1.16.0 sniffio-1.3.0 social-auth-app-django-5.0.0 social-auth-core-4.2.0 soupsieve-2.4.1 sqlparse-0.4.4 stack-data-0.6.2 terminaltables-3.1.10 toml-0.10.2 tomli-2.0.1 tomlkit-0.12.1 traitlets-5.9.0 twisted-23.8.0 txaio-23.1.1 typing-extensions-4.7.1 urllib3-2.0.4 uvicorn-0.17.6 uvloop-0.17.0 virtualenv-20.24.4 watchgod-0.8.2 wcwidth-0.2.6 webencodings-0.5.1 websockets-11.0.3 whitenoise-6.1.0 wrapt-1.15.0 zope-interface-6.0
```

```
$ pipdeptree -w fail
Warning!!! Possibly conflicting dependencies found:
* twisted==23.8.0
 - zope-interface [required: >=5, installed: ?]
------------------------------------------------------------------------
[...]
      - twisted [required: >=18.7, installed: 23.8.0]
        - attrs [required: >=21.3.0, installed: 23.1.0]
        - automat [required: >=0.8.0, installed: 22.10.0]
          - attrs [required: >=19.2.0, installed: 23.1.0]
          - six [required: Any, installed: 1.16.0]
        - constantly [required: >=15.1, installed: 15.1.0]
        - hyperlink [required: >=17.1.1, installed: 21.0.0]
          - idna [required: >=2.5, installed: 3.4]
        - incremental [required: >=22.10.0, installed: 22.10.0]
        - typing-extensions [required: >=3.10.0, installed: 4.7.1]
        - zope-interface [required: >=5, installed: ?]
```

### Twisted 22.10.0 (pipdeptree passes)

```
$ pip install "twisted<23.8.0"
Collecting twisted<23.8.0
  Downloading Twisted-22.10.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 16.7 MB/s eta 0:00:00
```

```
$ pipdeptree -w fail
[...]
- twisted [required: >=18.7, installed: 22.10.0]
        - attrs [required: >=19.2.0, installed: 23.1.0]
        - Automat [required: >=0.8.0, installed: 22.10.0]
          - attrs [required: >=19.2.0, installed: 23.1.0]
          - six [required: Any, installed: 1.16.0]
        - constantly [required: >=15.1, installed: 15.1.0]
        - hyperlink [required: >=17.1.1, installed: 21.0.0]
          - idna [required: >=2.5, installed: 3.4]
        - incremental [required: >=21.3.0, installed: 22.10.0]
        - typing-extensions [required: >=3.6.5, installed: 4.7.1]
        - zope.interface [required: >=4.4.2, installed: 6.0]
          - setuptools [required: Any, installed: 67.8.0]
```

**Comment by MatthijsBurgh** [comment] 2023-08-31 07:30
@bj00rn When you try this with `twisted==22.10.0`, does it still complain?

**Comment by bj00rn** [comment] 2023-08-31 07:41
> @bj00rn When you try this with `twisted==22.10.0`, does it still complain?

It works with 22.10.0. Edited and appended output in previous comment

**Comment by MatthijsBurgh** [comment] 2023-08-31 07:47
Thanks, IMO this seems to be related.

**Comment by glyph** [comment] 2023-08-31 17:21
OK, I can reproduce this on ubuntu 20.04 in a Docker container, but not on my host system (macOS 13.5.1)

**Comment by glyph** [comment] 2023-08-31 17:24
Also on 22.04, so it's not unique to that version, but, when I try to do this on 23.04, I get 
```
root@ea68146f21e0:/# pip install catkin-tools-document
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

which I believe points towards the root of the issue…

**Comment by glyph** [comment] 2023-08-31 17:34
Here's a script that will get you running on your desired system:

```
#!/bin/sh

apt update
apt install -y python3-venv
python3 -m venv /catkin-env
# shellcheck disable=1091
. /catkin-env/bin/activate
pip install --upgrade setuptools pip
pip install catkin-tools-document
catkin --help
```

The key thing here is:

- never install packages into your system Python path, that's for Debian & Ubuntu, not for you; as you can see in my previous coment, newer versions of Ubuntu will actively prevent you from doing this. always make a venv
- use a version of Setuptools and Pip that were released in the last 24 months, not one from early 2020

I think there *is* a bug in Twisted here, so I'm leaving this open, which is that we need a minimum version pin on setuptools that can resolve zope.interface according to whatever novel way the distribution is specified.  But such a fix on our end will break your 20.04 containers unless you're already following the venv best practices outlined above, and if you follow those, it'll work just fine today :).

**Comment by MatthijsBurgh** [comment] 2023-09-01 08:19
With `setuptools>=62` it does work, even without a virtual env. So @glyph I suggest you set that as the requirement on `setuptools`.

**Comment by glyph** [comment] 2023-09-01 17:27
Thanks @MatthijsBurgh !

**Comment by graingert** [comment] 2023-09-01 17:53
> which is that we need a minimum version pin on setuptools that can resolve zope.interface according to whatever novel way the distribution is specified

Twisted shouldn't depend on setuptools probably the fix is to change catkin-tools to not use deprecated pkg_resources

https://github.com/catkin/catkin_tools/issues/297#issuecomment-1703134179

**Comment by graingert** [comment] 2023-09-04 08:39
closing this as it's an issue with pkg_resources not twisted

**Closed as completed by graingert** 2023-09-04 08:39 UTC
Labels: bug

**Comment by AdamWill** [comment] 2023-10-27 19:02
Well, I'm seeing something along the same lines here. The difference seems to be that older twisted's METADATA file says something like `Requires-Dist: zope.interface (>=4.4.2)` , but twisted 23.8.0's METADATA file says `Requires-Dist: zope-interface>=5` (note the change from `zope.interface` to `zope-interface`). When doing a `python3 setup.py install` on something that requires twisted, it fails:

    Searching for zope-interface>=5
    Reading https://pypi.org/simple/zope-interface/
    No local packages or working download links found for zope-interface>=5

this is with setuptools 67.7.2. If I manually edit the METADATA file to say `zope.interface>=5`, it works fine.

twisted's `pyproject.yaml` specifies the dep with a period - `"zope.interface >= 5"` - so I don't know what's turning it into a dash by the time it reaches METADATA. But it wasn't happening before 23.8.0, and it does seem to cause problems.

**Comment by graingert** [comment] 2023-10-27 19:07
This is probably related to the switch to hatch

**Comment by glyph** [comment] 2023-10-27 19:19
> twisted's `pyproject.yaml` specifies the dep with a period - `"zope.interface >= 5"` - so I don't know what's turning it into a dash by the time it reaches METADATA. But it wasn't happening before 23.8.0, and it does seem to cause problems.

A different way to ask this question might be what *isn't* normalizing the dependency in versions of setuptools before 2022, given that name normalization was standardized in 2015... https://packaging.python.org/en/latest/specifications/name-normalization/

**Comment by AdamWill** [comment] 2023-10-27 22:33
as I said, I'm not using a particularly old version of setuptools. I'm using 67.7.2, that's from April this year. It's possible something in the 68 series fixes it, I guess, I can try and test with that later today.

The error message comes from setuptools `fetch_distribution`, here - https://github.com/pypa/setuptools/blob/main/setuptools/package_index.py#L672 . So I guess it is setuptools getting this wrong.

**Comment by AdamWill** [comment] 2023-10-27 22:38
If I throw in an exception on the failure path, this is the traceback:

    No local packages or working download links found for zope-interface>=5
    Traceback (most recent call last):
      File "/root/fedora_openqa/setup.py", line 10, in <module>
        setup(
      File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
               ^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
        super().run_command(command)
      File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.12/site-packages/setuptools/command/install.py", line 86, in run
        self.do_egg_install()
      File "/usr/lib/python3.12/site-packages/setuptools/command/install.py", line 143, in do_egg_install
        cmd.run(show_deprecation=False)
      File "/usr/lib/python3.12/site-packages/setuptools/command/easy_install.py", line 416, in run
        self.easy_install(spec, not self.no_deps)
      File "/usr/lib/python3.12/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        return self.install_item(None, spec, tmpdir, deps, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        self.process_distribution(spec, dist, deps)
      File "/usr/lib/python3.12/site-packages/setuptools/command/easy_install.py", line 750, in process_distribution
        distros = WorkingSet([]).resolve(
                  ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 827, in resolve
        dist = self._resolve_dist(
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
        dist = best[req.key] = env.best_match(
                               ^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1133, in best_match
        return self.obtain(req, installer)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1145, in obtain
        return installer(requirement)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/setuptools/command/easy_install.py", line 663, in easy_install
        dist = self.package_index.fetch_distribution(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/setuptools/package_index.py", line 678, in fetch_distribution
        raise ValueError("oh dear")

**Comment by AdamWill** [comment] 2023-10-27 23:30
setuptools 68.2.2 doesn't fix it.
