### ISSUE TITLE
How use rawDataReceived or setRawMode

### ISSUE THREAD

**Issue by lujiasheng1995** [twisted/twisted#11792] opened 2022-12-27 08:21 UTC
```
class TestProtocol(Protocol):
    def connectionMade(self):
        print 'Got connection from', self.transport.client

    def dataReceived(self, data):
            print(data)


class Test(Factory, HoneypotService):
    NAME = 'test'
    protocol = TestProtocol

    def __init__(self, config=None, logger=None):
        HoneypotService.__init__(self, config=config, logger=logger)
        self.port = 8888

    def getService(self):
        return internet.TCPServer(self.port, self)
```
When I use the telnet `127.0.0.1 8888` command to connect to this service, and input `abcdef`,Method dataReceived is executed twice,execute result is as follows:

output：
```
Got connection from
a
bacef
```
Is there any way to execute dataReceived only once, And the output information is abcdef. 
The output information is abcdef.
When I rewrite rawDataReceived, it doesn't trigger it

**Comment by adiroiban** [comment] 2022-12-27 10:14
This is by design. `dataReceived` is the low-level API that should be called as soon as data is available over the receive network queue.

You can expect that dataReceived to be execute once per each received byte.

You can implement higher level API to have a callback once per line  for example.
There is already a line receiver protocol implemented in Twisted.

I am closing this as not-an-issue.

We can continue the conversion over IRC/matrix/mailing list or GitHub Discussions.

**Closed as not planned by adiroiban** 2022-12-27 10:14 UTC
